Main/Controllers/ModelController.cs
Main/Program.cs
Repositories/ModelRepository.cs
Repositories/MotorizationRepository.cs
Services/ModelServices.cs

GetOneModelById 
DeleteOneModeleById
CreateOneModel
UpdateOneModelById

CRUD Models 

---

Services/AuthService.cs

add comment to Register()

---

Main/Controllers/BrandController.cs
Repositories/BrandRepository.cs
Services/BrandServices.cs

UpdateBrandById
GetOneBrandByIdAsync
DeleteOneBrandByIdAsync

Brand CRUD

---

IRepositories/IUserRepository.cs
IServices/IUserService.cs
Main/Controllers/UserController.cs
Main/Program.cs
Repositories/UserRepository.cs
Services/UserService.cs

Implementation DeleteUserById()

Implementation DeleteUserById()

---

Repositories/AuthRepository.cs
Repositories/Repositories.csproj
Utils/Constants/ROLE.cs

fix role par default à la creation d'un user

fix role par default à la creation d'un user

---

IRepositories/IUserRepository.cs
IServices/IUserService.cs
Main/Controllers/UserController.cs
Repositories/UserRepository.cs
Services/UserService.cs

Implementation GetUserById()

---

IRepositories/IUserRepository.cs
IServices/IUserService.cs
Main/Controllers/AuthController.cs
Main/Controllers/UserController.cs
Repositories/UserRepository.cs
Services/AuthService.cs
Services/UserService.cs
Utils/Constants/ROLE.cs

Implementation GetUserByRole()

Implementation GetUserByRole()

---

DTO/User/GetUserByNameDTO.cs
Main/Controllers/UserController.cs
Repositories/UserRepository.cs
Services/UserService.cs

Implemetation GetUsersByName()

Implemetation GetUsersByName()

---

CarShare-API.sln
DTO/CarPools/CarPoolSimpleIdDTO.cs
DTO/CarPools/CarpoolWithLocalizationID.cs
DTO/Localization/LocalizationDTO.cs
DTO/Localization/LocalizationIdDTO.cs
DTO/Localization/LocalizationWithCarDTO.cs
DTO/Localization/LocalizationWithCarpoolDTO.cs
DTO/Vehicles/VehicleSimpleDTO.cs
IRepositories/ILocalizationRepository.cs
Main/Program.cs
Repositories/DatabaseContext.cs
Repositories/LocalizationRepository.cs
Repositories/ModelRepository.cs
Repositories/MotorizationRepository.cs
Repositories/Repositories.csproj
RepositoriesTests/DbContextLocalizationTest.cs
RepositoriesTests/LocalizationRepositoryTests.cs
RepositoriesTests/RepositoriesTests.csproj

LOCALIZATION AND ILOCALIZATION 

---

IRepositories/IUserRepository.cs
IRepositories/IVehicleRepository.cs
Main/Controllers/UserController.cs
Main/Controllers/VehicleController.cs
Repositories/UserRepository.cs
Repositories/VehicleRepository.cs
Services/RentService.cs
Services/UserService.cs
Services/VehicleService.cs

Fix repartition des rôles

---

DTO/CarPoolPassenger/CreateCarPoolPassengerDTO.cs
DTO/CarPools/CreateOneCarPoolDTO.cs
DTO/CarPools/GetOneCarPoolDTO.cs
DTO/Rent/GetOneRentDTO.cs
IRepositories/ICarPoolPassengerRepository.cs
IRepositories/ICarPoolRepository.cs
IRepositories/IRentRepository.cs
IRepositories/IUserRepository.cs
IServices/ICarPoolPassengerService.cs
IServices/ICarPoolService.cs
IServices/IRentService.cs
IServices/IUserService.cs
Main/Controllers/CarPoolController.cs
Main/Controllers/CarPoolPassengerController.cs
Main/Controllers/RentController.cs
Main/Controllers/UserController.cs
Main/Controllers/VehicleController.cs
Main/Program.cs
Repositories/CarPoolPassengerRepository.cs
Repositories/CarPoolRepository.cs
Repositories/DateRepository.cs
Repositories/LocalizationRepository.cs
Repositories/RentRepository.cs
Repositories/UserRepository.cs
Services/CarPoolPassengerService.cs
Services/CarPoolService.cs
Services/RentService.cs
Services/UserService.cs

Implementation GetUserByCarPool() and necessaries creates

Implementation GetUserByCarPool() and necessaries creates

---

DTO/CarPoolPassenger/CreateCarPoolPassengerDTO.cs
DTO/CarPools/CreateOneCarPoolDTO.cs
DTO/CarPools/GetOneCarPoolDTO.cs
DTO/User/UpdateUserDTO.cs
IRepositories/ICarPoolPassengerRepository.cs
IRepositories/ICarPoolRepository.cs
IRepositories/IUserRepository.cs
IServices/ICarPoolPassengerService.cs
IServices/ICarPoolService.cs
IServices/IUserService.cs
Main/Controllers/CarPoolController.cs
Main/Controllers/CarPoolPassengerController.cs
Main/Controllers/UserController.cs
Main/Program.cs
Repositories/CarPoolPassengerRepository.cs
Repositories/CarPoolRepository.cs
Repositories/DateRepository.cs
Repositories/LocalizationRepository.cs
Repositories/UserRepository.cs
Services/CarPoolPassengerService.cs
Services/CarPoolService.cs
Services/UserService.cs

Implementation UpdateUser()

---

DTO/CarPoolPassenger/CreateCarPoolPassengerDTO.cs
DTO/CarPools/CreateOneCarPoolDTO.cs
DTO/CarPools/GetOneCarPoolDTO.cs
IRepositories/ICarPoolPassengerRepository.cs
IRepositories/ICarPoolRepository.cs
IRepositories/IUserRepository.cs
IServices/ICarPoolPassengerService.cs
IServices/ICarPoolService.cs
IServices/IUserService.cs
Main/Controllers/CarPoolController.cs
Main/Controllers/CarPoolPassengerController.cs
Main/Controllers/UserController.cs
Main/Program.cs
Repositories/CarPoolPassengerRepository.cs
Repositories/CarPoolRepository.cs
Repositories/DateRepository.cs
Repositories/LocalizationRepository.cs
Repositories/UserRepository.cs
Services/CarPoolPassengerService.cs
Services/CarPoolService.cs
Services/UserService.cs

Reverts toccoflorian/Digiliberte-back#41

Revert "Iplementation UpdateUser()"

---

IRepositories/IUserRepository.cs
Repositories/UserRepository.cs
Services/UserService.cs

Fix DeleteUser()

---

Main/Controllers/UserController.cs

[FIX] getUserByName()

---

Main/Controllers/CarPoolController.cs
Main/Controllers/VehicleController.cs
Repositories/CarPoolRepository.cs
Services/CarPoolService.cs

Adding new repo and services, changing create car pool logic for dates

[ADD] GetCarPoolByDriverId , CreateCarPool Fix

---

DTO/CarPoolPassenger/DeleteCarpoolPassengerDTO.cs
DTO/CarPoolPassenger/GetOneCarPoolPassengerDTO.cs
DTO/Rent/CreateRentDTO.cs
IRepositories/ICarPoolPassengerRepository.cs
IServices/ICarPoolPassengerService.cs
Main/Controllers/CarPoolPassengerController.cs
Repositories/CarPoolPassengerRepository.cs
Services/CarPoolPassengerService.cs
Services/CarPoolService.cs

Implementation DeleteCarpoolPassenger()

Implementation DeleteCarpoolPassenger()

---

DTO/CarPools/CreateCarpoolRequestDTO.cs
Main/Controllers/CarPoolController.cs

Creating CreateCarpoolRequestDTO , to be used in the createcarpool controller.

request DTO for carpool changes

---

DTO/Pagination/PageForkDTO.cs
IRepositories/ICarPoolPassengerRepository.cs
IServices/ICarPoolPassengerService.cs
Main/Controllers/CarPoolPassengerController.cs
Repositories/CarPoolPassengerRepository.cs
Repositories/UserRepository.cs
Services/CarPoolPassengerService.cs

Iplementation GetAllCarpoolPassenger()

Iplementation GetAllCarpoolPassenger()

---

IRepositories/ICarPoolRepository.cs
IServices/ICarPoolService.cs
Main/Controllers/CarPoolController.cs
Repositories/CarPoolPassengerRepository.cs
Repositories/CarPoolRepository.cs
Services/CarPoolService.cs

Implementation GetCarpoolByPassenger(), GetCarpoolByRent()

Implementation GetCarpoolByPassenger(), GetCarpoolByRent()

---

DTO/CarPools/GetCarpoolByDateDTO.cs
IRepositories/ICarPoolRepository.cs
IServices/ICarPoolService.cs
Main/Controllers/AuthController.cs
Main/Controllers/CarPoolController.cs
Repositories/CarPoolRepository.cs
Services/CarPoolService.cs

[ADD] GetCarpoolByDates()

---

IRepositories/ICarPoolRepository.cs
Main/Controllers/CarPoolController.cs
Repositories/CarPoolRepository.cs
Services/CarPoolPassengerService.cs
Services/CarPoolService.cs
Services/UserService.cs

[ADD] DeleteCarpool()

---

DTO/CarPools/GetOneCarPoolDTO.cs
DTO/CarPools/UpdateOneCarPoolDTO.cs
IRepositories/ICarPoolRepository.cs
IServices/ICarPoolService.cs
Main/Controllers/CarPoolController.cs
Repositories/CarPoolRepository.cs
Services/CarPoolService.cs

[ADD] UpdateCarpool()

---

Repositories/RentRepository.cs

[FIX] Ajout de UserId getAllRent()

[FIX] Ajout de UserId getAllRent()

---

IRepositories/ICarPoolRepository.cs
Repositories/CarPoolRepository.cs

[ADD] Ajout de GetCarPoolTypeByIdAsync()

[ADD] Ajout de GetCarPoolTypeByIdAsync()

---

DTO/Rent/CreateRentDTO.cs
DTO/Rent/GetOneRentByVehicleIdDTO.cs
DTO/Rent/IsVehicleRentedDTO.cs
DTO/Rent/UpdateRentDTO.cs
DTO/Rent/UpdateRentRequestDTO.cs
IRepositories/IDateRepository.cs
IRepositories/IRentRepository.cs
IServices/IRentService.cs
Main/Controllers/RentController.cs
Main/Controllers/TestController.cs
Main/Program.cs
Repositories/DateRepository.cs
Repositories/Helper/RentHelper.cs
Repositories/RentRepository.cs
Services/RentService.cs

principaux services faits et repos

MERGE DEVELOP RENT , RESTE CONTROLLEUR A FAIRE, VITE FAIT

---

Main/Controllers/CarPoolPassengerController.cs
Repositories/CarPoolPassengerRepository.cs
Services/CarPoolPassengerService.cs

GetPassengersByCarPool

---

Main/Controllers/CarPoolPassengerController.cs
Repositories/CarPoolPassengerRepository.cs
Services/CarPoolPassengerService.cs

Comments done
Conditions alf done

GetPassengersByUser

---

DTO/CarPoolPassenger/UpdateCarPoolPassengerControllerDTO.cs
DTO/CarPoolPassenger/UpdateCarPoolPassengerDTO.cs
IRepositories/ICarPoolPassengerRepository.cs
IServices/ICarPoolPassengerService.cs
Main/Controllers/CarPoolPassengerController.cs
Repositories/CarPoolPassengerRepository.cs
Services/CarPoolPassengerService.cs

[ADD] UpdateCarpoolPassenger()

[ADD] UpdateCarpoolPassenger()

---

DTO/CarPoolPassenger/GetOneCarPoolPassengerDTO.cs
DTO/CarPools/GetCarPoolSimpleWithPassengerDTO.cs
DTO/CarPools/GetOneCarPoolDTO.cs
DTO/Rent/GetOneRentWithCarPoolDTO.cs
IRepositories/ICarPoolRepository.cs
IRepositories/IRentRepository.cs
IServices/IRentService.cs
Main/Controllers/CarPoolController.cs
Main/Controllers/RentController.cs
Repositories/CarPoolRepository.cs
Repositories/DateRepository.cs
Repositories/RentRepository.cs
Services/RentService.cs

Adding Comentary and all controllers
Missing DELETE AND GETBYVEHICLEID

Develop cedric MERGE
